### ISSUE TITLE
There is a mistake when the program calculate base_psnr during testing.

### ISSUE THREAD

**Issue by y18810919727** [yuke93/RL-Restore#11]
I got different base_psnr value when I modify test_batch(2048 for default) during test RL model. It seems that there is a bug in your code.
 
In ```211 row of environment.py```, the function ```def update_test_data(self):``` modifies the variable ```self.base_psnr``` to the base_psnr of current batch. But in the first round to execute``` 471 row of  agent.py ```:
``` reward_all, psnr_all, base_psnr = self.env.act_test(action_test, step=m)```
The returned base_psnr is equal to the base_psnr of the whole dataset which is defined in ```row 70 of environment.py``` 
```            
for k in range(len(self.data_all)):
        self.base_psnr += psnr_cal(self.data_all[k, ...], self.label_all[k, ...])
self.base_psnr /= len(self.data_all)
```
So the final average of base_psnr in each batch may has a slight difference with the true base_psnr .

**Comment by yuke93** [comment]
Hi @y18810919727 ,

Thanks a lot for reporting this bug!

I have fixed it by changing `self.data_all` and `self.label_all` to `self.data_test` and `self.label_test`, respectively. In this way, the base PSNR represents the current batch in the first round.

Thanks again! ;)
