### ISSUE TITLE
'noise_combination' undefined near line 17 column 13

### ISSUE THREAD

**Issue by kevin1One** [yuke93/RL-Restore#15]
'noise_combination' undefined near line 17 column 13

called from
    /destination/data/train/generate_train.m at line 17 column 11

**Comment by yuke93** [comment]
@kevin1One You may check whether "noise_combination.m" is in the same path as "generate_train.m". Also, you need to run the code in `/destination/data/train/`, otherwise you have to run `addpath('/destination/data/train/')` before you excute the script.
