### ISSUE TITLE
New application scenarios

### ISSUE THREAD

**Issue by noob0523** [yuke93/RL-Restore#18]
Hello, can the modified code be applied to the distortion repair of single-channel grayscale images?

**Comment by yuke93** [comment]
@noob0523 Hi, our framework assumes a three-channel color input. You may replicate the gray channel to get a three-channel input.

**Comment by noob0523** [comment]
Thank you very much for your reply. My current research object is a single-channel medical image. I hope to use your framework for image enhancement. If the input gray image is not modified, which parts of the code can be modified to achieve this? Kindly ask for your advice

**Comment by yuke93** [comment]
@noob0523 If you wish to test your own single-channel images, you may put your image in "data/test/mine/". Then you can modify the function `update_test_mine()` in "dqn/environment.py" to turn `my_img` from one channel into three channels. 
Note: I use OpenCV to read the image, so there is a chance that the image is turned into three channels by default. You may try to run the code before you modify it.

**Comment by noob0523** [comment]
Thank you, I used the model trained on the DIV2K data set you provided to test my single-channel image, but the repair result can only be called tool12 once and then terminated. Can replacing the training set with my single-channel image and introducing distortion solve this problem?

**Comment by yuke93** [comment]
@noob0523 When you test a high-resolution image, it is possible that only one tool is selected as most regions do not have severe distortions. I am not sure whether training on your own dataset can work better. There must be a gap between medical images and natural images, as well as their distortions. If the gap is too large, our pre-trained tools may not solve your problem well.

**Comment by noob0523** [comment]
Thank you for your suggestions. The model I trained on my data set still does not solve my problem well. I want to replace the CNN network in the toolbox with a network that is more suitable for my problem. If I want to replace the tool, I need Which part of the code is modified?

**Comment by yuke93** [comment]
@noob0523 You may put your CNN in "toolbox/" and change the code in "dqn/environment.py" accordingly.
https://github.com/yuke93/RL-Restore/blob/dd1463dfed37073005b85822961adf5a2bbca528/dqn/environment.py#L78
