### ISSUE TITLE
hello，thank for your code

### ISSUE THREAD

**Issue by zmxzsl** [yuke93/RL-Restore#4]
我有个问题就是，您选用的工具如何调整每个工具的Distortion Level Interval

**Comment by yuke93** [comment]
@zmxzsl Thanks for your question. The distortion level interval is pre-defined. If you want to adjust it, you have to re-train the models in the toolbox using the data with your desired distortion levels.

**Comment by zmxzsl** [comment]
> @zmxzsl Thanks for your question. The distortion level interval is pre-defined. If you want to adjust it, you have to re-train the models in the toolbox using the data with your desired distortion levels.

Thanks for your answer.
