### ISSUE TITLE
dataset question

### ISSUE THREAD

**Issue by wanghai111** [yuke93/RL-Restore#7]
How to make my data set as a training set？

**Comment by yuke93** [comment]
You may refer to `data/train/generate_train.m`, which is used to generate training data.

**Comment by wanghai111** [comment]
It can be made using the dataset you provide, but my own dataset will show insufficient memory.

**Comment by yuke93** [comment]
It seems your dataset is large. You may divide your dataset into some subsets, and you can generate one hdf5 file for each subset.

**Comment by wanghai111** [comment]
I am using the DIV2K800 dataset, your link to download the DIV2K dataset can be made successfully, but the DIV2K dataset I downloaded is not successful.

**Comment by yuke93** [comment]
Yes. I have down-sampled the original images by different scales, so the original images have larger sizes.
