### ISSUE TITLE
Prepare train data set

### ISSUE THREAD

**Issue by runningyz** [yuke93/RL-Restore#9]
How could I prepare my train data set without Matlab on my ubuntu server?Will you provide a hdf5 file or a python script to prepare data set?

**Comment by runningyz** [comment]
Thank you for your reply !

Ke YU <notifications@github.com> 于2019年5月8日周三 下午9:39写道：

**Comment by liujianzhao6328057** [comment]
Hi, when I am generating the train set, the array is so large that the ram is not enough . Have the python version finished yet ? thank you very much .

**Comment by yuke93** [comment]
Hi @liujianzhao6328057,  

I have a Python version at hand. The code is written by @padmaksha18 and revised by me, although I haven't checked whether it works correctly for training. You may leave your email here so that I can send the codes to you. Thanks.

**Comment by liujianzhao6328057** [comment]
Thank you very much and this is my email liujianzhao6328057@126.com


| |
黛·烛爇短檠
|
|
邮箱：liujianzhao6328057@126.com
|

签名由 网易邮箱大师 定制

On 07/26/2019 14:30, Ke YU wrote:

Hi @liujianzhao6328057,

I have a Python version at hand. The code is written by @padmaksha18 and revised by me, although I haven't checked whether it works correctly for training. You may leave your email here so that I can send the codes to you. Thanks.

**Comment by yuke93** [comment]
@liujianzhao6328057 I have sent the code to you ;)

**Comment by Jeozhao** [comment]
Hi，@yuke93 .
      Could you please send me the python version of the code?
      My e-mail is zzy_hust@126.com.
      Thanks!

**Comment by liujianzhao6328057** [comment]
@Jeozhao  I have sent to you

**Comment by Jeozhao** [comment]
@liujianzhao6328057 Thank you very much！

**Comment by yuke93** [comment]
You may download the Python code [here](https://drive.google.com/open?id=1SbaEwsgL_A4syDWRaT1UFDXGcQkfE3Ei). :)

**Comment by padmaksha18** [comment]
Hi Yuke,

Hope you are doing well. You will be happy to know that I joined the
Virginia Tech for masters and higher studies in this field. Looking forward
to do a PhD as well.

Thanks and Regards
Padmaksha Roy

**Comment by yuke93** [comment]
Hi @padmaksha18 ,

Cooool! Congratulations! Maybe we can meet at some conference soon :)

Best,
Ke Yu

**Comment by padmaksha18** [comment]
Hahaha..sure... but I think I will need time to establish myself here...
are you doing a post doc now? Please be in touch.

Thanks
Padmaksha

**Comment by noob0523** [comment]
Hi，@yuke93 .
Could you please send me the python script to prepare data set?
My e-mail is 962357439@qq.com
